### ISSUE TITLE
Cambios endpoint "Delete pending RentalAgreement"

### ISSUE THREAD

**Issue by BrianSaavL** [crvargasu/backend-error500#56]
¿Cuál es el problema?
Necesito que se realicen cambios al endpoint usado para rechazar un pending rental agreement (issue #40) 

`DELETE /api/v1/rental_agreements/pending/delete`

¿Cómo necesitas que sea el endpoint para tu solución?
para que este funcione como un `PUT` donde se entreguen las razones para rechazar y se realice una actualizacion del estado de este a `denied` con las `reasons` ingresadas como parametros de la request

Muéstranos un ejemplo de enpoint para poder replicarlo

Recibe 
```
    {
        userId: id_user,
        RentalAgreementId: id_rental,
        reasons: text
    }
```
Retorna
```
    {
         successfully rejected the rental agreement...
    }
```

**Comment by crvargasu** [comment]
No te funciona el endpoint? El código ya debería soportar esa request. Lo probé en local y funciona bien.
prueba algo asi
```
{ "api_v1_rental_agreement": { "user_id": 9, "rental_agreement_id": 3,"reasons": "text" } }
```

**Comment by BrianSaavL** [comment]
Toda la razón, no había probado meterle los reasons y asumi que había que hacer algún cambio. Cierro esto
