### ISSUE TITLE
calification

### ISSUE THREAD

**Issue by Fernan-tess** [crvargasu/backend-error500#58]
**¿Cuál es el problema?**
Necesito que un endpoint que soporte el método `get` para calificar a un usuario

**¿Cómo necesitas que sea el endpoint para tu solución?**
Necesito que le pasen el id del usuario a calificar y una califocacion

**Muéstranos un ejemplo de enpoint para poder replicarlo**
```
{
user_id:  3
calification: 5
}
```

**Comment by itmunoz** [comment]
Ya se hizo una issue para postear calificaciones: https://github.com/crvargasu/backend-error500/issues/26
Revisa si te sirve o si hay algo más que necesites.

**Comment by crvargasu** [comment]
Se detectó que habia un error al calcular las mean reviews. El error fue corregido.
