### ISSUE TITLE
endpoint index RentalAgreement with status "pending"

### ISSUE THREAD

**Issue by Tngarrido** [crvargasu/backend-error500#64]
**¿Cuál es el problema?**
Necesito que el endpoint GET de /api/v1/rental_agreements/pending/:id retorne los objetos completos de los usuarios que involucra el contrato, es decir, necesito datos del lessor y leaseholder involucrados

**Muéstranos un ejemplo de enpoint para poder replicarlo**
```
{"RentalAgreement":
   {
   "id":3,
  "status":"denied",
   "lessor": {name: "name user", phone: +56912345678, ...},
   "leaseholder": {name: "name user", phone: +56912345678, ...},
   "reasons":"porque si",
   "offer_price":"1000.0",
   "days_for_week": 3
  }
}
```

**Comment by BrianSaavL** [comment]
tambien si puedes agregar los contratos con status "denied" en esta respuesta, que decidimos dejarlos como parte de esta vista

**Comment by itmunoz** [comment]
Listo. También agregué los denied a la lista
