### ISSUE TITLE
Filtro leaseholders

### ISSUE THREAD

**Issue by Tngarrido** [crvargasu/backend-error500#74]
**¿Cuál es el problema?**
Necesito que el endpoint '/api/v1/leaseholders' sólo retorne aquellos leaseholder donde se cumpla las siguientes dos condiciones: 1) capacity - (total de contratos aceptados (aproved) del lesaholder) > 1 y 2) leaseholder haya sido aceptado por el admins (status = true?)

**Muéstranos un ejemplo de enpoint para poder replicarlo**
```
{
leaseholders: [{
    name: test,
    address: direc,
    edad: 24
...
    }, ...]
}
```

**Comment by crvargasu** [comment]
corrección: capacity - (total de contratos aceptados (aproved) del lesaholder) > 0.

Hecho
