### ISSUE TITLE
Active Admin

### ISSUE THREAD

**Issue by Tngarrido** [crvargasu/backend-error500#75]
**¿Cuál es el problema?**
Necesito un nuevo tipo de usuario Admin, que soporte SignIn/Logout/SignUp. Además, necesito un endpoint que podría ser algo como: '/api/v1/leaseholders/pending', que me retorne todos los nuevos leaseholder que aún no han sido aceptados por Admin (status= false?).

**Muéstranos un ejemplo de enpoint SinIn para poder replicarlo**
```
{
user: {
    email: test,
    type: "admin"
    }
}
```
**Muéstranos un ejemplo de enpoint '/api/v1/leaseholders/pending' para poder replicarlo**
```
{
leaseholders: [{
    id_picture_front: "url",
    id_picture_back: "url",
    property_account: "url",
    user: {email: test,
    name: "name",
    phone: "569 12345678",
    status: false
    ....},
    }, ....]
}
```

**Comment by itmunoz** [comment]
Listos la configuración de admin para sign_in y sign_up. Solo debes indicar que type: 'admin' en sign_up

**Comment by itmunoz** [comment]
Listo el leaseholder. Se me olvidó avisar por acá
